spring:
  datasource:
    url: jdbc:mysql://localhost:3306/example_spring_boot
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  thymeleaf:
    cache: false
  mvc:
    format:
      date: yyyy-MM-dd
